Create nodes with hotkeys while linking
xodio/xod pull request #2068
Opened 2020-11-10 18:22 UTC by brusherru

It closes #1770

2020-11-11 10:36 UTC, evgenykochetkov commented on packages/xod-project/src/constants.js
> +export const NODE_KIND = {
I don't think this needs to live in `xod-project`

2020-11-11 16:58 UTC, evgenykochetkov requested changes
Trying to create a tweak from a generic pin results in an incorrect patch.
Trying to create a constant node from a generic pin crashes the IDE.

2020-11-12 15:08 UTC, evgenykochetkov commented on packages/xod-project/src/patchPathUtils.js
> +export const getConstantNodeType = type =>
I'd add checks for generic types here

2020-11-12 15:08 UTC, evgenykochetkov commented on packages/xod-project/src/patchPathUtils.js
> +export const getTweakPatchPath = R.ifElse(
and here

2020-11-12 16:43 UTC, brusherru commented on packages/xod-project/src/patchPathUtils.js
> +export const getConstantNodeType = type =>
👌

2020-11-12 16:43 UTC, brusherru commented on packages/xod-project/src/patchPathUtils.js
> +export const getTweakPatchPath = R.ifElse(
👌

2020-11-13 10:57 UTC, nkrkv approved these changes
:heart:

2020-11-13 14:42 UTC, evgenykochetkov approved these changes

2020-11-13 15:51 UTC, merged