Table logs feature: collect, view and save tabular data
xodio/xod pull request #2098
Opened 2021-02-05 21:02 UTC by brusherru

There is no issue 🙈 

- Adds new node `xod/debug/table-log`
- Adds new "Table Log" tab with table-view of the collected data

## How to test:
1. Place the new `xod/debug/table-log` node
2. Place `join` node
3. Set `\t` as a delimiter
4. Link some data sources (sensors / `system-time` / `sine-wave` / etc)
5. Link join with `table-log` node
6. Link pulse source to the `PUSH` pin of `table-log`
6. Run the program: simulate or upload with debugging
7. Double click on the `table-log` node to drill-down in the special tab "Table Log"

Also, you can place any amount of `table-log` nodes, send pulses to the `NEW` to create new sheets, `table-log` nodes might be placed inside other nodes, source labels are generated from labels of the nodes.

2021-02-05 21:06 UTC, brusherru commented
Also, I have an idea of how to improve source labels and make it looks like:
- `@/rootPatch`
- `@/rootPatch > unlabeled (nodeId) #1`
- `@/rootPatch > unlabeled (nodeId) #2`
- `@/rootPatch > my-label #2`
- `@/rootPatch > DELETED (nodeId)`

2021-02-08 14:55 UTC, nkrkv requested changes
The source drop-down looks reversed (right to left) on my machine:

![image](https://user-images.githubusercontent.com/146383/107236464-cb81ed00-6a36-11eb-8318-aaed759098c2.png)

2021-02-08 14:55 UTC, nkrkv commented on workspace/__lib__/xod/debug/table-log/patch.xodp
> +  "description": "Shows incoming values in the realtime, when a debug session is active",
This should be updated. I’m thinking about:

> Collects values as table rows and tables as sheets. Useful to conduct measurement sessions and then analyze the data gathered in spreadsheet software.

The pins require docs too.

2021-02-08 14:55 UTC, nkrkv commented on workspace/__lib__/xod/debug/table-log/patch.xodp
> +        "__out__": "On Boot"
This should be "Never" by default. Otherwise we always start with the second sheet

2021-02-08 14:55 UTC, nkrkv commented on packages/xod-client/src/debugger/selectors.js
> +            } rows`;
I’d suggest more coincise form: “1 sheets, 13 rows”

2021-02-08 15:12 UTC, evgenykochetkov commented
Not sure if this is intentional, but "Table Log" tab jumps to the rightmost position when drilling down.
https://user-images.githubusercontent.com/2527093/107238433-e2c1da00-6a38-11eb-91c2-ba1033c8b091.mov

2021-02-08 15:28 UTC, evgenykochetkov commented on packages/xod-client/src/editor/reducer.js
> +      // offset: { x: 0, y: 0, }, // TODO: Why do we need it?! :-(
👀

2021-02-12 11:27 UTC, nkrkv approved these changes
:fire:

2021-02-12 14:05 UTC, evgenykochetkov approved these changes

2021-02-15 17:24 UTC, merged