Do not load project with invalid patch paths
xodio/xod pull request #2099
Opened 2021-02-15 17:25 UTC by brusherru

It fixes #2097

2021-02-16 10:48 UTC, nkrkv requested changes

2021-02-16 10:48 UTC, nkrkv commented on packages/xod-fs/src/messages.js
> +    title: 'Can not load some patches',
```suggestion
    title: 'Cannot load some patches',
```

2021-02-16 10:48 UTC, nkrkv commented on packages/xod-fs/src/messages.js
> +    note: `Some patches have an invalid patch paths: ${patchPaths.join(', ')}`,
I’d limit this array with an ellipsis if more than, say, three items. Otherwise, UI will explode

2021-02-16 10:48 UTC, nkrkv commented on packages/xod-fs/src/messages.js
> +      'Open the "__lib__" directory in your workspace and ensure that listed directory names is valid. Only lowercase latin alphabet, numbers and minus between other symbols are alowed.',
```suggestion
      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hyphens are allowed.',
```

2021-02-17 11:15 UTC, nkrkv approved these changes
:+1: 

See one more typo below though

2021-02-17 11:15 UTC, nkrkv commented on packages/xod-fs/src/messages.js
> +      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hypens are alowed.',
```suggestion
      'Open the "__lib__" directory in your workspace and ensure that listed directory names are valid. Only lowercase latin alphabet, numbers, and hypens are allowed.',
```

2021-02-24 12:17 UTC, evgenykochetkov approved these changes
LGTM!

2021-02-24 14:56 UTC, merged